---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Assemble a node from a PODM compliant JSON info/requirements file
      rsd_compose:
        specfile: specfile/simple.json
        state: assembled
